# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
# write your code here (for Python default syntax)
arr = [0] * 1000
sys.getsizeof(arr)

8056

In [3]:
# write your code here (for numpy syntax)
arr = np.zeros(1000, dtype=np.int8)
arr.nbytes

1000

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [4]:
array = np.array([1, 2, 3, 4, 5 ,6, 7])
array[[0, 2, -1]]

array([1, 3, 7])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [6]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
# write your code here
np.sum(array[[0, 1, 4, 7]])

np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [3]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [4]:
# write your code here
np.mean(A, axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [5]:
# write your code here
np.std(A, axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [6]:
# write your code here
np.sum(A, axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [11]:
# write your code here
A[[0, 1], :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [12]:
# write your code here
A[[0, 2, 4], :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [9]:
%%timeit

[i for i in range(1000000)]

171 ms ± 5.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%%timeit

np.arange(1000000)

6.35 ms ± 1.43 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Task 6.2

In [32]:
%%timeit

def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

unknown_signature(vector1, vector2)

1.89 μs ± 172 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [31]:
%%timeit

def numpy_dot(vector1, vector2):
    vector1 = np.array(vector1)
    vector2 = np.array(vector2)
    result = np.dot(vector1, vector2)
    return result
    
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

numpy_dot(vector1, vector2)

12.6 μs ± 864 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Task 6.3

In [17]:
%%timeit

def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

unknown_signature(matrix1, matrix2)

4.86 μs ± 805 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
%%timeit

def numpy_signature(matrix1, matrix2):
    matrix1_np = np.array(matrix1)
    matrix2_np = np.array(matrix2)
    result_np = matrix1_np * matrix2_np
    return result_np.tolist()

# Define matrices
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

# Perform operation
numpy_signature(matrix1, matrix2)


25.3 μs ± 2.81 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Task 6.4

In [25]:
%%timeit

def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

unknown_signature(lst)

1.14 μs ± 24.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [24]:
%%timeit

def numpy_signature(lst):
    lst_np = np.array(lst)
    result = np.mean(lst_np)
    return result

lst = [1, 2, 3, 4, 5]

numpy_signature(lst)

54.8 μs ± 14.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [13]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [14]:
# write your numpy code here
def numpy_signature(lst, mask, new_value):
    lst_np = np.array(lst)
    mask_np = np.array(mask)
    lst_np[mask_np] = new_value
    return lst_np.tolist()

# Define the inputs
lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
numpy_signature(lst, mask, new_value)

[0, 2, 0, 4, 0]

### Task 7.2

In [15]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [18]:
# write your numpy code here
def numpy_signature(lst1, lst2):

    lst1_np = np.array(lst1)
    lst2_np = np.array(lst2)
    
    bitwise_complement = ~lst1_np
    bitwise_and = lst1_np & lst2_np
    bitwise_or = lst1_np | lst2_np
    
    return bitwise_complement.tolist(), bitwise_and.tolist(), bitwise_or.tolist()

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]

result_bitwise_complement, result_bitwise_and, result_bitwise_or = numpy_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

### Task 7.3 Optional

In [19]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [20]:
# write your numpy code here
def numpy_signature(lst):
    array = np.array(lst)
    mask = (array % 2 == 0) & ((array % 3 == 0) | (array > 10))
    modified_array = (array[mask] ^ 7) + 2
    return modified_array

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]